
@host = http://localhost:5137
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZ2l2ZW5fbmFtZSI6ImNhcmxvczEyMyIsImp0aSI6IjFiNTJjNDBjLTE4N2ItNDJkMS1iNzhhLTJjZWFhM2FhYzI1ZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBoeXNpY2lhbiIsImV4cCI6MTc3MjM0NTk3MiwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.HlQp415kvVIhD092wlfgZmWrs4q2n5P3Q26PYtCO1IU

GET http://localhost:5137/