@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsImdpdmVuX25hbWUiOiJDYXJsb3MiLCJqdGkiOiJlZTc2Mjc0Yi1hN2FkLTQ3ZjEtOWNhZS1iZGJjYmYxZDU0NmEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NjQ1MDc1MiwiaXNzIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSIsImF1ZCI6IkZpbmxheV9QaGFybWFWaWdpbGFuY2UifQ.AWyPp9IGQ45PlWp1b54AeEe5bmX-d22-ILlJLvFariU

POST {{host}}/api/Catalog/activate/vaccine/1
Content-Type:  application/json
Authorization: Bearer {{token}}



####



POST {{host}}/api/Catalog/activate/symptom/1
Content-Type:  application/json
Authorization: Bearer {{token}}