@host = http://localhost:5137
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkNhcmxvcyIsImp0aSI6IjBhNjRjMzhmLTQzZDctNDExMS1iMTkzLWNkY2U1MGUzNzQ5OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc2ODk4MTk2LCJpc3MiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIiwiYXVkIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSJ9.xwGoR57_Tg7804kyCY1aQd0dwaS6Oq0-Dw4s6NSCWMs


POST {{host}}/api/Catalog/register/vaccine
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "name": "SOberana",
  "type": 0,
  "code": "TC12323",
  "isActive": true,
  "description": "A vaccine developed by the Finlay Institute in Cuba, based on a recombinant protein subunit platform. It has shown efficacy in preventing symptomatic COVID-19 and severe disease.",
  "approvalDate": "2020-04-03T09:18:28.095Z"
}

