@host = http://localhost:5137

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZ2l2ZW5fbmFtZSI6IkphYmVsIiwianRpIjoiYzZlMTI4NjAtZmU2Mi00NmIxLThmN2UtYjExNGJhMTMxMjc3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWVkaWNhbFJldmlld2VyIiwiZXhwIjoxNzc1NjAzMjEzLCJpc3MiOiJGaW5sYXlfUGhhcm1hVmlnaWxhbmNlIiwiYXVkIjoiRmlubGF5X1BoYXJtYVZpZ2lsYW5jZSJ9.8ysMTOLphkTtN_LyzYeMOh79HjhCwEH3kFBccT9tfSU 


POST {{host}}/api/Report/createPublic
Content-Type:  application/json

{
  "reportDate": "2026-04-04T19:13:59.418Z",
  "reporter": {
    "fullName": "Jabel",
    "reporterRelationship": "Self",
    "identityNumber": "03041868002",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "provinceId": 1,
    "municipalityId": 2,
    "phoneNumber": "55664266",
    "email": "12aidenpearces@gmail.com"
  },
  "vaccinatedSubject": {
    "fullName": "Jabel",
    "identityNumber": "03041868002",
    "dateOfBirth": "2003-04-18T18:13:59.418Z",
    "gender": 1,
    "isPregnant": false,
    "provinceId": 2,
    "municipalityId": 4,
    "healthArea": "string",
    "address": "string",
    "phoneNumber": "55664266",
    "email": "12aidenpearces@gmail.com",
    "currentMedications": "string",
    "allergies": "string",
    "medicalHistory": "string"
  },
  "vaccinations": [
    {
      "vaccineId": "08dea0df-93de-4c04-8f03-6d24751c22df",
      "batchNumber": "qweqweq",
      "site": "leftarm",
      "doseNumber": 5,
      "administrationDate": "2026-04-02T18:13:59.418Z",
      "vaccinationCenter": "string"
    }
  ],
  "adverseEvents": [
    {
      "startDate": "2026-04-03T12:13:59.418Z",
      "description": "string",
      "visitedDoctor": true,
      "wentToEmergencyRoom": true,
      "permanentDisability": true,
      "isLifeThreatening": false,
      "resultedInDeath": false,
      "deathDate": null,
      "currentStatus": "Recovered",
      "symptoms": [
        "08dea0de-29fa-4ca4-8afc-af4cafc58a4c"
      ]
    }
  ]
}


####

POST {{host}}/api/Report/createMedical
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "reportDate": "2026-04-06T19:39:17.845Z",
  "vaccinatedSubject": {
    "fullName": "Fred",
    "identityNumber": "03041868164",
    "dateOfBirth": "2003-04-18T19:39:17.845Z",
    "gender": 1,
    "isPregnant": false,
    "provinceId": 1,
    "municipalityId": 1
  },
  "vaccinations": [
    {
      "vaccineId": 1,
      "batchNumber": "1212",
      "site": 0,
      "doseNumber": 2,
      "administrationDate": "2026-03-07T19:39:17.845Z",
      "vaccinationCenter": "string"
    }
  ],
  "adverseEvents": [
    {
      "startDate": "2026-04-05T19:39:17.845Z",
      "description": "string",
      "visitedDoctor": true,
      "wentToEmergencyRoom": true,
      "permanentDisability": true,
      "isLifeThreatening": true,
      "resultedInDeath": true,
      "deathDate": "2026-04-05T19:39:17.845Z",
      "currentStatus": 0,
      "symptoms": [
        1,2,3
      ]
    }
  ],
  "causality": 0,
  "clinicalSignificance": 0
}